# Generated by Django 4.1 on 2022-10-08 14:08

from django.db import migrations
from django.db.models import F
from django.utils.text import slugify


def slugify_product(apps, schema_editor):
    Product = apps.get_model("store", "Product")

    for product in Product.objects.filter(slug=''):
        product.slug = slugify(product.name)
        product.save()

    # TODO check why this not working
    # Product.objects.filter(slug='').update(slug=slugify(F('name')))


def undo_slugify(app, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_slug'),
    ]

    operations = [
        migrations.RunPython(slugify_product, undo_slugify)
    ]
